// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEY67kEKlqDewg1w_dlb68e6mCeNDwnyE',
    appId: '1:912818404647:web:67de83be43ba924225fd02',
    messagingSenderId: '912818404647',
    projectId: 'magzhass-4fd0a',
    authDomain: 'magzhass-4fd0a.firebaseapp.com',
    storageBucket: 'magzhass-4fd0a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCle4_CZTVmFmquOcD94HlYxOThLXqXg3Y',
    appId: '1:912818404647:android:2f1753739f53ac5d25fd02',
    messagingSenderId: '912818404647',
    projectId: 'magzhass-4fd0a',
    storageBucket: 'magzhass-4fd0a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQgjBvYxmpP7v_BPiXqKPhF0q23N8UWrM',
    appId: '1:912818404647:ios:4393ae3c46da803725fd02',
    messagingSenderId: '912818404647',
    projectId: 'magzhass-4fd0a',
    storageBucket: 'magzhass-4fd0a.firebasestorage.app',
    iosBundleId: 'com.example.solaifrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQgjBvYxmpP7v_BPiXqKPhF0q23N8UWrM',
    appId: '1:912818404647:ios:4393ae3c46da803725fd02',
    messagingSenderId: '912818404647',
    projectId: 'magzhass-4fd0a',
    storageBucket: 'magzhass-4fd0a.firebasestorage.app',
    iosBundleId: 'com.example.solaifrontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEY67kEKlqDewg1w_dlb68e6mCeNDwnyE',
    appId: '1:912818404647:web:5169bfda7df166d625fd02',
    messagingSenderId: '912818404647',
    projectId: 'magzhass-4fd0a',
    authDomain: 'magzhass-4fd0a.firebaseapp.com',
    storageBucket: 'magzhass-4fd0a.firebasestorage.app',
  );
}
